title: shaunGF's Homepage
page-top-title: shaunGF
top-section-bg-text: Do what you love, and love what you do.
home-subtitle: shaunGF&ICer;
copyright-text: '&copy; shaunGF 2023-2025. All Rights Reserved.'
